# Загальна інформація про проект
site_name: Документація до страждань
site_author: Ільніцький Ілля
site_description: 'НеПроста та Незрозуміла документація для власних страждань.'

# Налаштування зовнішнього вигляду
theme: material

name: material
language: uk # Додамо українську мову для елементів інтерфейсу

# Налаштування структури навігаційного меню
nav:
  - 'Головна': 'index.md'
  - 'Посібник користувача':
    - 'Встановлення': 'guide/installation.md'
    - 'Приклади використання': 'guide/usage.md'
  - 'Про проєкт': 'about.md'